// Shared social preview images (Open Graph / LinkedIn / Facebook / X).
// Next.js merges metadata shallowly, so any page that defines its own `openGraph` /
// `twitter` object must include these images itself, otherwise networks get no thumbnail.
// The files are generated by scripts/make-og.mjs; bump OG_VERSION there (new file name)
// whenever the image changes, because networks cache previews by image URL.
const SITE = 'https://www.pbix.pl';
const PL = `${SITE}/og-2026-09e-pl.png`;
const EN = `${SITE}/og-2026-09e-en.png`;

const image = (url: string, alt: string) => ({ url, secureUrl: url, width: 1200, height: 630, alt, type: 'image/png' });

export const OG_IMAGES = [image(PL, 'Radosław Sobczak – szkolenia Power BI, Excel, AI i VBA dla firm')];
export const OG_IMAGES_EN = [image(EN, 'Radosław Sobczak – Power BI, Excel, AI and VBA corporate training')];

export const TWITTER_IMAGES = [PL];
export const TWITTER_IMAGES_EN = [EN];
